### PR TITLE
Step 4 work

### PR DESCRIPTION
**Pull request by Lam-Richard**
**What is the purpose of this PR?**
To rewrite disasterCode to be faster, < 0.07s (This is the first PR, I have to do another one later that is < 0.0001s)
**What changes did you make? Why?**
I rewrote disasterCode into getUniquePrimeFactors to speed it up, things I did include storing a list of prime factors up to the number I was calculating for, and stopping iterations at half of `i` since the the square root is always less than or equal to half. I got the following time on my local machine (having issues SSH-ing into the nuft server), and I doubt my mac is more performant than the server:

```
(base) richard@Richards-MBP-9 learnsomething % python3 prime.py                                                                                                         
Average execution time after 5 runs: 0.035121 seconds
```
**What bugs did you find while testing?**
Didn't find much

**How does this make the code faster?**
There are less loop iterations

**How much headroom do you have?**
If headroom means the difference between the limit and the actual then i have 0.07 - 0.035121  = 0.03s of headroom

### CODE REVIEW

**Comment by Lam-Richard** [comment]
Running the code on the NUFT server yields:

```
(intern-project) rlh0080@fintechclub:~/learnsomething$ python3 prime.py
Average execution time after 5 runs: 0.039397 seconds
```

Which is also <0.07s

**Comment by Lam-Richard** [comment]
**What is the purpose of this PR?**
To rewrite my rewritten disasterCode to be faster than < 0.0001s
**What changes did you make? Why?**
I rewrote my algorithm because it turns out it was not fast enough. I also rewrote it in CPP because it turns out Python wasn't fast enough. I also changed the format in which my algorithm stored the computed unique prime factors for numbers in [2,2500) to make it just barely be faster than the requirement:

```
(base) rlh0080@fintechclub:~/learnsomething$ ./A
0.00009 seconds
```

(I somehow highly doubt that people who have passed Step 4 are both 1 actually doing what the problem statement asks and 2 are doing it under 0.0001s)

**What bugs did you find while testing?**
Didn't find much

**How much headroom do you have?**
0.00001s worth of headroom..? (0.0001 - 0.00009 = 0.00001)

**Comment by echavemann** [comment]
you need to run `prime.py` and it needs to output the time under 0.0001

**Review by minnce — APPROVED** [review]
looks good

**Pull request merged**
