### PR TITLE
Step 3: Used two pointer solution to write a faster version of max_area

### PR DESCRIPTION
**Pull request by Lam-Richard**
# General
**What is the purpose of this PR?**
After reading and understanding the code, I realized that improved.py should be a faster version of baseline.py (since they started out as identical files). I also recognized that the function max_area was being computed with two for loops when a faster solution existed (two pointers).
**What changes did you make? Why?**
I rewrote improved.py to use two pointers to compute max_area because it has a better Big O runtime (linear instead of quadratic).
**What bugs did you find while testing?**
Upon running `task test` I ran into the below error; I did some Googling to understand the problem, comments are below.

# This PR Specific
**What was the bug you found?**
max_area is very slow because it uses two nested loops.
**How did you address it?**
use two pointers instead.
**What did you struggle with?**
Running task test, probably because I have a mac.
**Is there anything you would change about this step?**
Not sure what the purpose of us not being able to see the tests were, can't use just test TLE or something?
**What was the code given to you by the tests?**
Not sure, because of the error below:

```
task: [test] poetry run python3 test.py
The currently activated Python version 3.8.8 is not supported by the project (^3.11).
Trying to find and use a compatible version. 
Using python3 (3.11.0)
Traceback (most recent call last):
  File "/Users/richard/Desktop/learnsomething/src/test.py", line 1, in <module>
    from pyarmor_runtime_000000 import __pyarmor__
  File "/Users/richard/Desktop/learnsomething/src/pyarmor_runtime_000000/__init__.py", line 2, in <module>
    from .pyarmor_runtime import __pyarmor__
ImportError: dlopen(/Users/richard/Desktop/learnsomething/src/pyarmor_runtime_000000/pyarmor_runtime.so, 0x0002): tried: '/Users/richard/Desktop/learnsomething/src/pyarmor_runtime_000000/pyarmor_runtime.so' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/richard/Desktop/learnsomething/src/pyarmor_runtime_000000/pyarmor_runtime.so' (no such file), '/Users/richard/Desktop/learnsomething/src/pyarmor_runtime_000000/pyarmor_runtime.so' (not a mach-o file)
task: Failed to run task "test": exit status 1
```

Some Googling led me to [this link](https://github.com/dashingsoft/pyarmor/issues/1368) which seems to claim that whoever generated the python script used Linux to obfuscate the script, but I am trying to run the obfuscated script (in our case test.py) on macOS, which is causing a problem. In the error message itself we see it saying (not a mach-o file) at the path in my repo where an .so file exists which leads me to think this is the problem. Please let me know if you want me to debug this or if we can call this Step 3 complete...!

### CODE REVIEW

**Comment by minnce** [comment]
@echavemann pyarmor blowing up again, any ideas why?

**Comment by echavemann** [comment]
`The currently activated Python version 3.8.8 is not supported by the project (^3.11).
Trying to find and use a compatible version. `

**Comment by echavemann** [comment]
why do we have 3.8.8

**Comment by echavemann** [comment]
pls bump to 11.0+

**Comment by Lam-Richard** [comment]
Wait its says ```Using python3 (3.11.0)``` so is that actually the problem or did you mean on your end

**Comment by Lam-Richard** [comment]
UPDATE: Running `task test` on the NUFT server gives the following:
```
(intern-project) rlh0080@fintechclub:~/learnsomething$ task test
task: [test] poetry run python3 test.py
All test cases passed!
Congratulations! Your Code is fast enough for production! Exit Code is:
```

**Review by echavemann — APPROVED** [review]

**Review by minnce — APPROVED** [review]

**Pull request merged**
